# Java Gradle CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-java/ for more details
#
version: 2.1

jobs:
  build:
    parameters:
      docker_image:
        type: string
        default: ""
    docker:
      # Reference: https://circleci.com/docs/2.0/circleci-images/
      - image: << parameters.docker_image >>

    working_directory: ~/repo

    environment:
      # Customize the JVM maximum heap limit
      JVM_OPTS: -Xmx3200m
      TERM: dumb
      WGRIB: /home/circleci/repo/wgrib
      GIT_LFS_SKIP_SMUDGE: 1
      RESOURCE_FILENAMES: |
        "CF2_20150706_092531.grb"
        "fh.000_tl.press_ar.octanti"
        "gfsanl_3_20170512_0000_000.grb2"
        "issue22.grb"

    steps:
      - checkout

      # Print some diagnostic info
      - run:
          name: Print diagnostic info
          command: |
              echo $(cat /etc/os-release)
              echo $(java -version)
              ls

      # Compute checksum of test resources
      - run:
          name: Compute checksum of test resources
          command: |
              resources_checksum=$(echo "${RESOURCE_FILENAMES" | sort | md5sum)
              echo Checksum of test resources: $resources_checksum
              echo $resources_checksum > RESOURCES_MD5

      # Download and cache dependencies
      - restore_cache:
          name: Restore Gradle from cache
          keys:
            - v1-dependencies-{{ checksum "build.gradle" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run: gradle dependencies

      # TODO Add caching for test resources
      - run:
          name: "Download test resources from Cloudsmith"
          environment:
            RES_DIR: src/test/resources
          command: |
            files=(
                "CF2_20150706_092531.grb"
                "fh.000_tl.press_ar.octanti"
                "gfsanl_3_20170512_0000_000.grb2"
                "issue22.grb"
            )
            for file in "${files[@]}"; do
                echo "Downloading file: ${file}"
                curl -1sLf "https://dl.cloudsmith.io/${CLOUDSMITH_TOKEN}/jgribx/grib-files/raw/files/${file}" --output "${RES_DIR}/${file}"
            done
            ls ${RES_DIR}

      - save_cache:
          name: Cache Gradle
          paths:
            - ~/.gradle
          key: v1-dependencies-{{ checksum "build.gradle" }}

      - restore_cache:
          name: Restore wgrib from cache
          keys:
            - v2-wgrib-cache

      # Download and install wgrib
      - run:
            name: Install wgrib
            command: |
                if [ ! -f "$WGRIB" ]; then
                    sudo apt install gcc
                    wget ftp://ftp.cpc.ncep.noaa.gov/wd51we/wgrib/wgrib.c
                    gcc --version
                    gcc wgrib.c -o wgrib
                fi
                # Print out wgrib version (note: running wgrib without arguments makes it return code 8)
                $WGRIB || [[ $? -eq 8 ]]

      # Cache wgrib binary
      - save_cache:
          name: Cache wgrib
          paths: /home/circleci/repo/wgrib
          key: v2-wgrib-cache

      # run tests!
      - run: gradle test

      - run:
            name: Save test results
            command: |
                mkdir -p ~/test-results/junit/
                find . -type f -regex ".*/build/test-results/.*xml" -exec cp {} ~/test-results/junit/ \;
                mkdir -p ~/test-results/junit/report/
                cp -r build/reports/tests/test ~/test-results/junit/report/
            when: always
      - store_test_results:
            path: ~/test-results
      - store_artifacts:
            path: ~/test-results/junit

      # Deploy application as JAR
      - run:
            name: Deploy Application
            command: |
                gradle jar
      - store_artifacts:
            path: build/libs

workflows:
  version: 2
  workflow:
    jobs:
      - build:
          matrix:
            parameters:
              docker_image: ["cimg/openjdk:8.0", "cimg/openjdk:11.0"]
