/*
 * ============================================================================
 * JGribX
 * ============================================================================
 * Written by Andrew Spiteri <andrew.spiteri@um.edu.mt>
 * Adapted from JGRIB: http://jgrib.sourceforge.net/
 * 
 * Licensed under MIT: https://github.com/spidru/JGribX/blob/master/LICENSE
 * ============================================================================
 */
package mt.edu.um.cf2.jgribx

/**
 * 02/06/2017   Andrew Spiteri      initial version
 */
object GribCodes {
	enum class DataRepresentation {
		GRID_POINT_DATA_SIMPLE_PACKING,
		MATRIX_VALUE_AT_GRID_POINT_SIMPLE_PACKING,
		GRID_POINT_DATA_COMPLEX_PACKING,
		GRID_POINT_DATA_COMPLEX_PACKING_AND_SPATIAL_DIFFERENCING
	}

	/**
	 * Returns the name of the originating centre corresponding to the specified ID.
	 * Source: [http://www-lehre.informatik.uni-osnabrueck.de/~fbstark/diplom/docs/data/GRIB/index.html](http://www-lehre.informatik.uni-osnabrueck.de/~fbstark/diplom/docs/data/GRIB/index.html)
	 * @param id
	 * @return the name of the originating centre corresponding to the specified ID
	 */
	fun getCentreName(id: Int): String = when (id) {
		1, 2, 3 -> "Melbourne (WMC)"
		4, 5, 6 -> "Moscow (WMC)"
		7 -> "US National Weather Service, National Centers for Environmental Prediction (NCEP)"
		8 -> "US National Weather Service Telecommunications Gateway (NWSTG)"
		9 -> "US National Weather Service - Other"
		10, 11 -> "Cairo (RSMC/RAFC)"
		12, 13 -> "Dakar (RSMC/RAFC)"
		14, 15 -> "Nairobi (RSMC/RAFC)"
		18, 19 -> "Tunis-Casablanca (RSMC)"
		20 -> "Las Palmas (RAFC)"
		21 -> "Algiers (RSMC)"
		22 -> "ACMAD"
		23 -> "Mozambique (NMC)"
		24 -> "Pretoria (RSMC)"
		25 -> "La Réunion (RSMC)"
		26, 27 -> "Khabarovsk (RSMC)"
		28, 29 -> "New Delhi (RSMC/RAFC)"
		30, 31 -> "Novosibirsk (RSMC)"
		32 -> "Tashkent (RSMC)"
		33 -> "Jeddah (RSMC)"
		34, 35 -> "Tokyo (RSMC), Japan Meterological Agency"
		36 -> "Bangkok"
		37 -> "Ulan Bator"
		38, 39 -> "Beijing (RSMC)"
		40 -> "Seoul"
		41, 42 -> "Buenos Aires (RSMC/RAFC)"
		43, 44 -> "Brasilia (RSMC/RAFC)"
		45 -> "Santiago"
		46 -> "Brazilian Space Agency - INPE"
		51 -> "Miami (RSMC/RAFC)"
		52 -> "Miami (RSMC/RAFC), National Hurricane Center"
		53, 54 -> "Montreal (RSMC)"
		55 -> "San Francisco"
		57 -> "US Air Force - Air Force Global Weather Central"
		58 -> "Fleet Numerical Meteorology and Oceanography Center, Monterey, CA, USA"
		59 -> "The NOAA Forecast Systems Laboratory, Boulder, CO, USA"
		60 -> "United States National Center for Atmospheric Research (NCAR)"
		64 -> "Honolulu"
		65, 66 -> "Darwin (RSMC)"
		67 -> "Melbourne (RSMC)"
		69, 70 -> "Wellington (RSMC/RAFC)"
		71 -> "Nadi (RSMC)"
		74, 75 -> "UK Meteorological Office, Bracknell (RSMC)"
		76 -> "Moscow (RSMC/RAFC)"
		78, 79 -> "Offenbach (RSMC)"
		80, 81 -> "Rome (RSMC)"
		82, 83 -> "Norrköping"
		85 -> "Toulouse (RSMC)"
		86 -> "Helsinki"
		87 -> "Belgrade"
		88 -> "Oslo"
		89 -> "Prague"
		90 -> "Episkopi"
		91 -> "Ankara"
		92 -> "Frankfurt/Main (RAFC)"
		93 -> "London (WAFC)"
		94 -> "Copenhagen"
		95 -> "Rota"
		96 -> "Athens"
		97 -> "European Space Agency (ESA)"
		98 -> "European Centre for Medium Range Weather Forecasts (ECMWF) (RSMC)"
		99 -> "De Bilt"
		110 -> "Hong Kong"
		160 -> "US NOAA/NESDIS"
		210 -> "Frascati (ESA/ESRIN)"
		211 -> "Lanion"
		212 -> "Lisboa"
		213 -> "Reykjavik"
		254 -> "EUMETSAT Operation Centre"
		255 -> "Missing value"
		else -> "Reserved"
	}

	fun getProcessName(id: Int): String = when (id) {
		2 -> "Ultra Violet Index Model"
		3 -> "NCEP/ARL Transport and Dispersion Model"
		4 -> "NCEP/ARL Smoke Model"
		5 -> "Satellite Derived Precipitation and temperatures, from IR (See PDS Octet 41... dfor specific satellite ID)"
		6 -> "NCEP/ARL Dust Model"
		10 -> "Global Wind-Wave Forecast Model"
		11 -> "Global Multi-Grid Wave Model (Static Grids)"
		12 -> "Probabilistic Storm Surge (P-Surge)"
		13 -> "Hurricane Multi-Grid Wave Model"
		14 -> "Extra-tropical Storm Surge Atlantic Domain"
		15 -> "Nearshore Wave Prediction System (NWPS)"
		16 -> "Extra-Tropical Storm Surge (ETSS)"
		17 -> "Extra-tropical Storm Surge Pacific Domain"
		18 -> "Probabilistic Extra-Tropical Storm Surge (P-ETSS)"
		19 -> "Limited-area Fine Mesh (LFM) analysis"
		20 -> "Extra-tropical Storm Surge Micronesia Domain"
		25 -> "Snow Cover Analysis"
		30 -> "Forecaster generated field"
		31 -> "Value added post processed field"
		42 -> "Global Optimum Interpolation Analysis (GOI) from GFS model"
		43 -> "Global Optimum Interpolation Analysis (GOI) from \"Final\" run "
		44 -> "Sea Surface Temperature Analysis"
		45 -> "Coastal Ocean Circulation Model"
		46 -> "HYCOM - Global"
		47 -> "HYCOM - North Pacific basin"
		48 -> "HYCOM - North Atlantic basin"
		49 -> "Ozone Analysis from TIROS Observations "
		52 -> "Ozone Analysis from Nimbus 7 Observations "
		53 -> "LFM-Fourth Order Forecast Model"
		64 -> "Regional Optimum Interpolation Analysis (ROI)"
		68 -> "80 wave triangular, 18-layer Spectral model from GFS model"
		69 -> "80 wave triangular, 18 layer Spectral model from \"Medium Range Forecast\" run"
		70 -> "Quasi-Lagrangian Hurricane Model (QLM)"
		71 -> "Hurricane Weather Research and Forecasting (HWRF) Model"
		72 -> "Hurricane Non-Hydrostatic Multiscale Model on the B Grid (HNMMB)"
		73 -> "Fog Forecast model - Ocean Prod. Center"
		74 -> "Gulf of Mexico Wind/Wave"
		75 -> "Gulf of Alaska Wind/Wave"
		76 -> "Bias corrected Medium Range Forecast"
		77 -> "126 wave triangular, 28 layer Spectral model from GFS model"
		78 -> "126 wave triangular, 28 layer Spectral model from \"Medium Range Forecast\" run"
		79 -> "Backup from the previous run"
		80 -> "62 wave triangular, 28 layer Spectral model from \"Medium Range Forecast\" run"
		81 -> "Analysis from GFS (Global Forecast System)"
		82 -> "Analysis from GDAS (Global Data Assimilation System)"
		83 -> "High Resolution Rapid Refresh (HRRR)"
		84 -> "MESO NAM Model (currently 12 km)"
		85 -> "Real Time Ocean Forecast System (RTOFS)"
		86 -> "Early Hurricane Wind Speed Probability Model"
		87 -> "CAC Ensemble Forecasts from Spectral (ENSMB)"
		88 -> "NOAA Wave Watch III (NWW3) Ocean Wave Model"
		89 -> "Non-hydrostatic Meso Model (NMM) (Currently 8 km)"
		90 -> "62 wave triangular, 28 layer spectral model extension of the \"Medium Range Forecast\" run"
		91 -> "62 wave triangular, 28 layer spectral model extension of the GFS model"
		92 -> "62 wave triangular, 28 layer spectral model run from the \"Medium Range Forecast\" final analysis"
		93 -> "62 wave triangular, 28 layer spectral model run from the T62 GDAS analysis of the \"Medium Range Forecast\" run"
		94 -> "T170/L42 Global Spectral Model from MRF run"
		95 -> "T126/L42 Global Spectral Model from MRF run"
		96 -> "Global Forecast System Model"
		98 -> "Climate Forecast System Model -- Atmospheric model (GFS) coupled to a multi level ocean model .   Currently GFS spectral model at T62, 64 levels coupled to 40 level MOM3 ocean model."
		99 -> "Miscellaneous Test ID"
		104 -> "National Blend GRIB"
		105 -> "Rapid Refresh (RAP)"
		106 -> "Reserved"
		107 -> "Global Ensemble Forecast System (GEFS)"
		108 -> "LAMP"
		109 -> "RTMA (Real Time Mesoscale Analysis)"
		110 -> "NAM Model - 15km version"
		111 -> "NAM model, generic resolution (Used in SREF processing)"
		112 -> "WRF-NMM model, generic resolution (Used in various runs) NMM=Nondydrostatic Mesoscale Model (NCEP)"
		113 -> "Products from NCEP SREF processing"
		114 -> "NAEFS Products from joined NCEP, CMC global ensembles"
		115 -> "Downscaled GFS from NAM eXtension"
		116 -> "WRF-EM model, generic resolution (Used in various runs) EM - Eulerian Mass-core (NCAR - aka Advanced Research WRF)"
		117 -> "NEMS GFS Aerosol Component"
		118 -> "URMA (UnRestricted Mesoscale Analysis)"
		119 -> "WAM (Whole Atmosphere Model)"
		120 -> "Ice Concentration Analysis"
		121 -> "Western North Atlantic Regional Wave Model"
		122 -> "Alaska Waters Regional Wave Model"
		123 -> "North Atlantic Hurricane Wave Model"
		124 -> "Eastern North Pacific Regional Wave Model"
		125 -> "North Pacific Hurricane Wave Model"
		126 -> "Sea Ice Forecast Model"
		127 -> "Lake Ice Forecast Model"
		128 -> "Global Ocean Forecast Model"
		129 -> "Global Ocean Data Analysis System (GODAS)"
		130 -> "Merge of fields from the RUC, NAM, and Spectral Model "
		131 -> "Great Lakes Wave Model"
		132 -> "High Resolution Ensemble Forecast (HREF)"
		133 -> "Great Lakes Short Range Wave Model"
		140 -> "North American Regional Reanalysis (NARR)"
		141 -> "Land Data Assimilation and Forecast System"
		150 -> "NWS River Forecast System (NWSRFS)"
		151 -> "NWS Flash Flood Guidance System (NWSFFGS)"
		152 -> "WSR-88D Stage II Precipitation Analysis"
		153 -> "WSR-88D Stage III Precipitation Analysis"
		180 -> "Quantitative Precipitation Forecast generated by NCEP"
		181 -> "River Forecast Center Quantitative Precipitation Forecast mosaic generated by NCEP"
		182 -> "River Forecast Center Quantitative Precipitation estimate mosaic generated by NCEP"
		183 -> "NDFD product generated by NCEP/HPC"
		184 -> "Climatological Calibrated Precipitation Analysis - CCPA"
		190 -> "National Convective Weather Diagnostic generated by NCEP/AWC"
		191 -> "Current Icing Potential automated product genterated by NCEP/AWC"
		192 -> "Analysis product from NCEP/AWC"
		193 -> "Forecast product from NCEP/AWC"
		195 -> "Climate Data Assimilation System 2 (CDAS2)"
		196 -> "Climate Data Assimilation System 2 (CDAS2) - used for regeneration runs"
		197 -> "Climate Data Assimilation System (CDAS)"
		198 -> "Climate Data Assimilation System (CDAS) - used for regeneration runs"
		199 -> "Climate Forecast System Reanalysis (CFSR) -- Atmospheric model (GFS) coupled to a multi level ocean, land and seaice model.   Currently GFS spectral model at T382, 64 levels coupled to 40 level MOM4 ocean model."
		200 -> "CPC Manual Forecast Product"
		201 -> "CPC Automated Product"
		210 -> "EPA Air Quality Forecast - Currently North East US domain"
		211 -> "EPA Air Quality Forecast - Currently Eastern US domain"
		215 -> "SPC Manual Forecast Product"
		220 -> "NCEP/OPC automated product"
		221, 222, 223, 224, 225, 226, 227, 228, 229, 230 -> "Reserved for WPC products"
		255 -> "Missing"
		else -> "Reserved"
	}
}